services:
  sonarqube:
    restart: always
    image: ${DOCKER_REGISTRY_URL}/sciling/sonarqube:10.4.1-community-with-extensions
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonarqube
    ports:
      - 127.0.0.1:19000:9000
    environment:
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-postgresql/sonar
      - SONAR_WEB_JAVAADDITIONALOPTS=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.19.0.jar=web
      - SONAR_CE_JAVAADDITIONALOPTS=-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.19.0.jar=ce
    volumes:
      - ./volumes/sonarqube/data:/opt/sonarqube/data
        #- ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
        #- ./volumes/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - sonarqube-postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  sonarqube-postgresql:
    restart: always
    image: sameersbn/postgresql:12-20200524
    container_name: sonarqube-postgresql
    environment:
      - DB_USER=sonar
      - DB_PASS=sonar
      - DB_NAME=sonar
      - DB_EXTENSION=pg_trgm
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
